language: c
matrix:
  include:
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
            - gcc-7
      env:
         - COMPILER="CC=gcc-7 && CXX=g++-7"
      before_install: eval "${COMPILER}"
      script: make

    - os: osx
      script: make

    - os: windows
      install: choco install mingw
      script: mingw32-make

deploy:
     provider: releases
     api_key: $DEPLOY_KEY
     file:
         - clay
     skip_cleanup: true
     on:
         repo: andseq/clay
         tags: true
